apiVersion: v1
kind: Service
metadata:
  name: app-blue-svc
  namespace: blue-green-demo
spec:
  selector:
    app: myapp
    version: blue  # This targets only blue pods
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
