apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-html
  namespace: blue-green-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Blue Version</title>
      <style>
        body {
          background-color: #1e88e5;
          color: white;
          font-family: Arial, sans-serif;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          margin: 0;
        }
        .container {
          text-align: center;
        }
        h1 {
          font-size: 4em;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>BLUE ENVIRONMENT</h1>
        <h2>Version 1.0</h2>
      </div>
    </body>
    </html>
